#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
# exec-once = waybar 
# exec-once = nm-applet
# exec-once = hyprpanel
exec-once = snappy-switcher --daemon
exec-once = clipse -listen
exec-once = fish -c 'set G502_ID (ratbagctl list | cut -f1 -d:); and ratbagctl "$G502_ID" profile active set 4'
