bezier = overshoot, 0.05, 0.9, 0.1, 1.9

layerrule = match:namespace rofi, animation popin 38%
layerrule = match:namespace rofi, dim_around on

layerrule = blur on, match:namespace powermenu
layerrule = ignore_alpha 0.2, match:namespace powermenu
layerrule = dim_around on, match:namespace powermenu
layerrule = match:namespace powermenu, animation popin

layerrule = match:namespace pybar-bar, blur on
layerrule = ignore_alpha 0.8, match:namespace pybar-bar

# Global gtk4-layer-shell blur
layerrule = blur on, match:class gtk4-layer-shell
layerrule = blur_popups on, match:class gtk4-layer-shell
layerrule = ignore_alpha 0.2, match:class gtk4-layer-shell

