
#Background
background {
  monitor =
  path = $HOME/Pictures/Wallapers/totoro.jpg
  color = rgba(25,20,20,1.0)
  blur_passes = 5
}

general {
  ignore_empty_input = true
  fail_timeout = 1000
}

animations {
  bezier = ease, 0.25, 0.1, 0.25, 1
  animation = fadeIn, 1, 0.9, ease
  animation = fadeOut, 0, 0, 0
}
shape {
  monitor =
  xray = false
  size = 17%, 35%
  color = rgba(250,250,250, 0.3)
  rounding = 30
  position = 0
  halign = center
  valign = center
}

# Time

label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%a, %-d %B %Y")"
  font_size = 20
  shadow_passes = 3
  shadow_size = 2
  position = 0, 5%
  halign = center
  valign = center
}

label {
  monitor =
  text = cmd[update:1000] echo "$TIME"
  font_size = 60
  position = 0,10% 
  shadow_passes = 3
  shadow_size = 2
  halign = center
  valign = center
}


# User

label {
  monitor =
  text = 
  position = -5%,-4%
  halign = center
  valign = center
}

label {
  monitor =
  text = <i><span>$USER</span></i>
  position = 0,-4%
  halign = center
  valign = center
}

shape {
  monitor =
  size = 12%, 3%
  color = rgba(74,189,255, 0.2)
  rounding = -1
  position = 0, -4%
  halign = center
  valign = center
}


# Password

label {
  monitor =
  text = 
  position = -5%,-8%
  halign = center
  valign = center
}

input-field {
    monitor =
    size = 12%, 3%
    outline_thickness = 0
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(255, 255, 255, 0)
    inner_color = rgba(74,189,255, 0.2)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    font_color = rgb(200, 200, 200)
    capslock_color = rgba(240, 136, 77, 0.3)
    fade_on_empty = false
    placeholder_text = <i><span foreground="##ffffff99">Enter Password</span></i>
    hide_input = false
    position = 0, -8%
    halign = center
    valign = center
}
