# Theme: Bold Hues
#   Description: A clean contrasty theme in tones of Pinks, Violets, Blues
#

$neonPink = rgb(f72585)
$indigoBloom = rgb(7209b7)
$vividRoyal = rgb(3A0CA3)
$electricSapphire = rgb(4361EE)
$skyAqua = rgb(4cc9f0)

# Neutral Dark Colours
$graphite = rgb(302b27)
$graphitephiteLite = rgb(2e2f2f)
$inkBlack = rgb(051014)
$midnightViolet = rgb(16001e)

# Neutral Light Colours
$linen =rgb(f9ebe0)
$petalFrost = rgb(f9cff2)
$lavenderMist = rgb(f8f0fb)
