# Nord theme for kitty
# Adapted from Konsole's Utterly-Nord colorscheme

foreground #eceff4
background #2e3440
cursor #d8deea
selection_background #434c5e
selection_foreground #eceff4

# black
color0 #4c566a
color8 #4c566a

# red
color1 #bf616a
color9 #bf616a

# green
color2 #a3be8c
color10 #a3be8c

# yellow
color3 #ebcb8b
color11 #ebcb8b

# blue
color4 #5e81ac
color12 #5e81ac

# magenta
color5 #b48ead
color13 #b48ead

# cyan
color6 #81a1c1
color14 #81a1c1

# white
color7 #d8deea
color15 #d8deea
